//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaMarket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public Nullable<int> IdItem { get; set; }
        public string PathOriginal { get; set; }
        public string PathPreview { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
