//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viamarket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int idItem { get; set; }
        public string title { get; set; }
        public string folderPicturesUrl { get; set; }
        public string description { get; set; }
        public string idUser { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> idCurrency { get; set; }
        public Nullable<int> idCategory { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Category Category { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
