//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaMarket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Image = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string IdAspNetUsers { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdCurrency { get; set; }
        public int IdCategory { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Category Category { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Image> Image { get; set; }
    }
}
