// <auto-generated />
namespace viamarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class contact3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact3));
        
        string IMigrationMetadata.Id
        {
            get { return "201406021412015_contact3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
